# Generated by Django 2.2.5 on 2020-04-09 20:27

from django.db import migrations, models
import food.models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtype',
            name='name',
            field=models.CharField(choices=[('STARTER', 0), ('MAIN', 1), ('DESSERT', 2), ('DRINK', 3)], default=food.models.FoodTypeEnum(0), max_length=20),
        ),
    ]
